// frontend/app/login/page.jsx
'use client';

import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '../../lib/supabaseClient';

export default function LoginPage() {
    const router = useRouter();

    const [isLogin, setIsLogin] = useState(true);
    const [email, setEmail] = useState('');
    const [senha, setSenha] = useState('');
    const [apelido, setApelido] = useState('');
    const [tipoUsuario, setTipoUsuario] = useState('comprador'); // NOVO: Estado para o tipo de conta
    const [loading, setLoading] = useState(false);
    const [erro, setErro] = useState('');

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setErro('');

        try {
            if (isLogin) {
                // 🔥 LÓGICA DE LOGIN
                const { data, error } = await supabase.auth.signInWithPassword({
                    email: email,
                    password: senha,
                });

                if (error) throw error;

                const { data: perfil } = await supabase
                    .from('perfis')
                    .select('tipo_usuario')
                    .eq('id', data.user.id)
                    .single();

                if (perfil?.tipo_usuario === 'vendedor') {
                    router.push('/admin/novo-leilao');
                } else {
                    router.push('/');
                }

            } else {
                // ✨ LÓGICA DE CADASTRO BLINDADA

                // 1. Verifica se o apelido já existe ANTES de criar a conta
                const { data: apelidoEmUso } = await supabase
                    .from('perfis')
                    .select('apelido')
                    .eq('apelido', apelido)
                    .maybeSingle();

                if (apelidoEmUso) {
                    throw new Error('Esse apelido já está em uso! Escolha outro.');
                }

                // 2. Se o apelido está livre, cria a conta no Auth
                const { data, error } = await supabase.auth.signUp({
                    email: email,
                    password: senha,
                });

                if (error) throw error;

                // 3. Salva o perfil com a certeza de que não vai dar erro
                if (data.user) {
                    const { error: erroPerfil } = await supabase
                        .from('perfis')
                        .insert([
                            { id: data.user.id, apelido: apelido, tipo_usuario: tipoUsuario }
                        ]);

                    if (erroPerfil) throw erroPerfil; // Agora, se der erro aqui, a tela avisa!
                }

                alert(`Conta de ${tipoUsuario.toUpperCase()} criada com sucesso! Faça login.`);
                setIsLogin(true);
            }
        } catch (error) {
            // Qualquer erro (seja de e-mail, senha fraca ou apelido) cai aqui e aparece vermelho na tela
            setErro(error.message || 'Ocorreu um erro.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div
            className="min-h-screen bg-[#121212] flex flex-col justify-center items-center p-4 font-sans text-gray-100">
            <div className="absolute top-8 left-8">
                <Link href="/"
                      className="text-gray-400 hover:text-orange-500 font-bold flex items-center gap-2 transition-colors">
                    <span>←</span> Voltar para a Vitrine
                </Link>
            </div>

            <div className="w-full max-w-md bg-gray-800 rounded-2xl shadow-2xl border border-gray-700 p-8">

                <div className="text-center mb-8">
                    <h1 className="text-4xl font-black text-white tracking-tight">Box<span
                        className="text-orange-500">64</span></h1>
                    <p className="text-gray-400 mt-2 font-medium">
                        {isLogin ? 'Acesso restrito.' : 'Escolha seu caminho.'}
                    </p>
                </div>

                {erro && (
                    <div
                        className="mb-4 bg-red-900/50 text-red-300 p-3 rounded-lg border border-red-700 text-sm font-semibold text-center">
                        ⚠️ {erro}
                    </div>
                )}

                <form onSubmit={handleSubmit} className="space-y-5">

                    {/* ESCOLHA DE CONTA (Só no Cadastro) */}
                    {!isLogin && (
                        <div className="flex gap-4 mb-4">
                            <label
                                className={`flex-1 cursor-pointer border-2 rounded-xl p-4 text-center transition-all ${tipoUsuario === 'comprador' ? 'border-orange-500 bg-orange-500/10' : 'border-gray-700 bg-gray-900'}`}>
                                <input type="radio" name="tipo" value="comprador" className="hidden"
                                       onChange={() => setTipoUsuario('comprador')}/>
                                <span
                                    className={`block font-bold ${tipoUsuario === 'comprador' ? 'text-orange-500' : 'text-gray-400'}`}>🛍️ Quero Comprar</span>
                            </label>

                            <label
                                className={`flex-1 cursor-pointer border-2 rounded-xl p-4 text-center transition-all ${tipoUsuario === 'vendedor' ? 'border-orange-500 bg-orange-500/10' : 'border-gray-700 bg-gray-900'}`}>
                                <input type="radio" name="tipo" value="vendedor" className="hidden"
                                       onChange={() => setTipoUsuario('vendedor')}/>
                                <span
                                    className={`block font-bold ${tipoUsuario === 'vendedor' ? 'text-orange-500' : 'text-gray-400'}`}>🏷️ Quero Vender</span>
                            </label>
                        </div>
                    )}

                    {!isLogin && (
                        <div>
                            <label className="block text-sm text-gray-400 mb-1 font-semibold">Como quer ser
                                chamado?</label>
                            <input type="text" required value={apelido} onChange={(e) => setApelido(e.target.value)}
                                   placeholder="Ex: ColecionadorBR"
                                   className="w-full bg-gray-900 border border-gray-700 rounded-lg p-3 text-white focus:ring-2 focus:ring-orange-500 outline-none"/>
                        </div>
                    )}

                    <div>
                        <label className="block text-sm text-gray-400 mb-1 font-semibold">E-mail</label>
                        <input type="email" required value={email} onChange={(e) => setEmail(e.target.value)}
                               placeholder="seu@email.com"
                               className="w-full bg-gray-900 border border-gray-700 rounded-lg p-3 text-white focus:ring-2 focus:ring-orange-500 outline-none"/>
                    </div>

                    <div>
                        <label className="block text-sm text-gray-400 mb-1 font-semibold">Senha</label>
                        <input type="password" required value={senha} onChange={(e) => setSenha(e.target.value)}
                               placeholder="••••••••"
                               className="w-full bg-gray-900 border border-gray-700 rounded-lg p-3 text-white focus:ring-2 focus:ring-orange-500 outline-none"/>
                    </div>

                    <button type="submit" disabled={loading}
                            className="w-full bg-orange-600 hover:bg-orange-500 disabled:bg-gray-600 text-white font-bold text-lg py-3 rounded-xl transition-all shadow-[0_0_15px_rgba(234,88,12,0.3)] mt-4">
                        {loading ? 'Processando...' : (isLogin ? 'ENTRAR' : 'CRIAR CONTA')}
                    </button>
                </form>

                <div className="mt-8 text-center border-t border-gray-700 pt-6">
                    <button onClick={() => {
                        setIsLogin(!isLogin);
                        setErro('');
                    }} type="button" className="text-orange-500 font-bold hover:underline focus:outline-none">
                        {isLogin ? "Criar nova conta" : "Já tenho uma conta"}
                    </button>
                </div>

            </div>
        </div>
    );
}

// src/views/Login.vue
<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { supabase } from '../supabase.js';

const router = useRouter();
const email = ref('');
const password = ref('');
const fullName = ref('');
const role = ref('buyer'); // 'buyer' ou 'seller'
const isLoading = ref(false);
const isRegisterMode = ref(false);

const handleAuth = async () => {
  isLoading.value = true;
  try {
    if (isRegisterMode.value) {
      // Criação de Conta
      const { data, error } = await supabase.auth.signUp({
        email: email.value,
        password: password.value,
        options: {
          data: {
            full_name: fullName.value,
            role: role.value
          }
        }
      });
      if (error) throw error;
      alert('Conta criada com sucesso! Verifique seu e-mail (se habilitado) ou tente entrar agora.');
      isRegisterMode.value = false;
      password.value = '';
    } else {
      // Login
      const { data, error } = await supabase.auth.signInWithPassword({
        email: email.value,
        password: password.value,
      });
      if (error) throw error;
      
      // O router guard automático fará a proteção agora
      router.push('/vitrine');
    }
  } catch (error) {
    alert('Erro: ' + error.message);
    console.error(error);
  } finally {
    isLoading.value = false;
  }
};
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-zinc-950 relative overflow-hidden px-4">
    
    <!-- Elementos Decorativos de Fundo (Blur) -->
    <div class="absolute top-1/4 left-1/4 w-96 h-96 bg-red-600/10 rounded-full blur-[100px] pointer-events-none"></div>
    <div class="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-600/5 rounded-full blur-[100px] pointer-events-none"></div>

    <div class="w-full max-w-md z-10 relative">
      
      <!-- Logotipo Centralizado -->
      <div class="flex justify-center mb-8">
        <router-link to="/" class="flex items-center gap-2">
          <i class="pi pi-box text-red-500 text-3xl"></i>
          <span class="font-bold text-3xl tracking-tight text-white uppercase italic">Box 64</span>
        </router-link>
      </div>

      <!-- Card de Login -->
      <div class="bg-zinc-900/80 backdrop-blur-xl border border-zinc-800 rounded-2xl p-8 shadow-2xl">
        <h2 class="text-2xl font-bold text-white mb-2 text-center">
          {{ isRegisterMode ? 'Criar Nova Conta' : 'Bem-vindo de volta' }}
        </h2>
        <p class="text-zinc-400 text-sm text-center mb-8">
          {{ isRegisterMode ? 'Cadastre-se para participar dos leilões' : 'Entre com sua conta para dar lances exclusivos' }}
        </p>

        <form @submit.prevent="handleAuth" class="space-y-5">
          
          <!-- Nome Completo (Apenas Cadastro) -->
          <div v-if="isRegisterMode">
            <label class="block text-sm font-medium text-zinc-400 mb-1.5">Nome Completo</label>
            <div class="relative">
              <span class="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-500">
                <i class="pi pi-user"></i>
              </span>
              <input 
                type="text" 
                v-model="fullName"
                required
                placeholder="Seu nome" 
                class="w-full bg-zinc-950 border border-zinc-700 rounded-lg py-3 pl-10 pr-4 text-white focus:outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 transition-colors"
              />
            </div>
          </div>

          <!-- Tipo de Conta (Apenas Cadastro) -->
          <div v-if="isRegisterMode" class="bg-zinc-950 border border-zinc-800 p-1.5 rounded-xl flex gap-1">
            <button 
              type="button"
              @click="role = 'buyer'"
              class="flex-1 py-2 px-4 rounded-lg text-sm font-bold transition-all flex items-center justify-center gap-2"
              :class="role === 'buyer' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-500 hover:text-zinc-300'"
            >
              <i class="pi pi-shopping-bag"></i> Sou Comprador
            </button>
            <button 
              type="button"
              @click="role = 'seller'"
              class="flex-1 py-2 px-4 rounded-lg text-sm font-bold transition-all flex items-center justify-center gap-2"
              :class="role === 'seller' ? 'bg-red-600 text-white shadow-sm' : 'text-zinc-500 hover:text-zinc-300'"
            >
              <i class="pi pi-tag"></i> Sou Vendedor
            </button>
          </div>

          <div>
            <label class="block text-sm font-medium text-zinc-400 mb-1.5">E-mail</label>
            <div class="relative">
              <span class="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-500">
                <i class="pi pi-envelope"></i>
              </span>
              <input 
                type="email" 
                v-model="email"
                required
                placeholder="seu@email.com" 
                class="w-full bg-zinc-950 border border-zinc-700 rounded-lg py-3 pl-10 pr-4 text-white focus:outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 transition-colors"
              />
            </div>
          </div>

          <div>
            <div class="flex justify-between items-center mb-1.5">
              <label class="block text-sm font-medium text-zinc-400">Senha</label>
              <a v-if="!isRegisterMode" href="#" class="text-xs text-red-500 hover:text-red-400 font-medium transition-colors">Esqueceu a senha?</a>
            </div>
            <div class="relative">
              <span class="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-500">
                <i class="pi pi-lock"></i>
              </span>
              <input 
                type="password" 
                v-model="password"
                required
                placeholder="••••••••" 
                minlength="6"
                class="w-full bg-zinc-950 border border-zinc-700 rounded-lg py-3 pl-10 pr-4 text-white focus:outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 transition-colors"
              />
            </div>
          </div>

          <button 
            type="submit" 
            :disabled="isLoading"
            class="w-full bg-red-600 hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold py-3 px-4 rounded-lg transition-colors shadow-lg shadow-red-600/20 mt-4 flex justify-center items-center gap-2"
          >
            <i v-if="isLoading" class="pi pi-spin pi-spinner"></i>
            <span v-else>{{ isRegisterMode ? 'Cadastrar e Entrar' : 'Entrar no Leilão' }}</span>
          </button>
        </form>

        <!-- Divisor -->
        <div class="mt-8 mb-6 flex items-center">
          <div class="flex-grow border-t border-zinc-800"></div>
          <span class="flex-shrink-0 mx-4 text-zinc-500 text-xs uppercase tracking-widest font-semibold">
            {{ isRegisterMode ? 'Já tem uma conta?' : 'Novo por aqui?' }}
          </span>
          <div class="flex-grow border-t border-zinc-800"></div>
        </div>

        <button @click="isRegisterMode = !isRegisterMode" class="w-full bg-zinc-950 hover:bg-zinc-800 text-zinc-300 font-medium py-3 px-4 rounded-lg border border-zinc-700 transition-colors">
          {{ isRegisterMode ? 'Fazer Login' : 'Criar conta grátis' }}
        </button>

      </div>
      
      <!-- Dica -->
      <p class="text-zinc-600 text-xs text-center mt-6">
        <span class="font-bold">Nota de Segurança:</span> O Supabase enviará um email de confirmação caso você cadastre uma nova conta.
      </p>

    </div>
  </div>
</template>
